# Generated by Django 5.2.5 on 2025-11-16 21:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('token', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Token de Confirmação')),
            ],
            options={
                'verbose_name': 'Inscrito na Newsletter',
                'verbose_name_plural': 'Inscritos na Newsletter',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem')),
                ('categoria', models.CharField(choices=[('evento', 'Evento'), ('projeto', 'Projeto'), ('conquista', 'Conquista'), ('parceria', 'Parceria'), ('noticia', 'Notícia Geral')], default='noticia', max_length=20, verbose_name='Categoria')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora em que a notícia será publicada automaticamente', verbose_name='Data de Publicação')),
                ('autor', models.CharField(blank=True, max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='VagaVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('requisitos', models.TextField(help_text='Um requisito por linha', verbose_name='Requisitos')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Tipo')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('horas_semanais', models.IntegerField(verbose_name='Horas Semanais')),
                ('duracao_minima', models.CharField(help_text='Ex: 3 meses, 6 meses, flexível', max_length=100, verbose_name='Duração Mínima')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada')], default='aberta', max_length=20, verbose_name='Status')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('vagas_totais', models.IntegerField(verbose_name='Total de Vagas')),
                ('vagas_disponiveis', models.IntegerField(verbose_name='Vagas Disponíveis')),
            ],
            options={
                'verbose_name': 'Vaga de Voluntariado',
                'verbose_name_plural': 'Vagas de Voluntariado',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name='Imagem')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária (horas)')),
                ('numero_encontros', models.IntegerField(verbose_name='Número de Encontros')),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('todos', 'Todos os níveis')], max_length=20, verbose_name='Nível')),
                ('vagas_totais', models.IntegerField(verbose_name='Total de Vagas')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('gratuito', models.BooleanField(default=False, verbose_name='Gratuito')),
                ('status', models.CharField(choices=[('disponivel', 'Vagas Disponíveis'), ('esgotado', 'Esgotado'), ('em_breve', 'Em Breve'), ('encerrado', 'Encerrado')], default='disponivel', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CandidaturaVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('profissao', models.CharField(blank=True, max_length=200, verbose_name='Profissão')),
                ('experiencia', models.TextField(blank=True, verbose_name='Experiência')),
                ('motivacao', models.TextField(verbose_name='Motivação')),
                ('disponibilidade', models.TextField(blank=True, verbose_name='Disponibilidade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('candidatou_em', models.DateTimeField(auto_now_add=True, verbose_name='Candidatou em')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='home.vagavoluntariado')),
            ],
            options={
                'verbose_name': 'Candidatura de Voluntariado',
                'verbose_name_plural': 'Candidaturas de Voluntariado',
                'ordering': ['-candidatou_em'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('experiencia', models.CharField(choices=[('nenhuma', 'Nenhuma experiência'), ('basica', 'Básica'), ('intermediaria', 'Intermediária'), ('avancada', 'Avançada')], max_length=20, verbose_name='Experiência')),
                ('motivacao', models.TextField(blank=True, verbose_name='Motivação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('inscrito_em', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='home.workshop')),
            ],
            options={
                'verbose_name': 'Inscrição em Workshop',
                'verbose_name_plural': 'Inscrições em Workshops',
                'ordering': ['-inscrito_em'],
                'unique_together': {('workshop', 'email')},
            },
        ),
    ]
