# Generated by Django 5.2.5 on 2025-10-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('inscrito_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Inscrição Newsletter',
                'verbose_name_plural': 'Inscrições Newsletter',
                'ordering': ['-inscrito_em'],
            },
        ),
        migrations.CreateModel(
            name='VagaVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField(help_text='Um requisito por linha')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('horas_semanais', models.IntegerField()),
                ('duracao_minima', models.CharField(help_text='Ex: 3 meses, 6 meses, flexível', max_length=100)),
                ('vagas_disponiveis', models.IntegerField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada')], default='aberta', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaga de Voluntariado',
                'verbose_name_plural': 'Vagas de Voluntariado',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='workshops/')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('carga_horaria', models.IntegerField(help_text='Carga horária em horas')),
                ('numero_encontros', models.IntegerField()),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('todos', 'Todos os níveis')], max_length=20)),
                ('vagas_totais', models.IntegerField()),
                ('vagas_ocupadas', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gratuito', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('disponivel', 'Vagas Disponíveis'), ('esgotado', 'Esgotado'), ('em_breve', 'Em Breve'), ('encerrado', 'Encerrado')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CandidaturaVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=200)),
                ('experiencia', models.TextField(blank=True)),
                ('motivacao', models.TextField()),
                ('disponibilidade', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('candidatou_em', models.DateTimeField(auto_now_add=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='home.vagavoluntariado')),
            ],
            options={
                'verbose_name': 'Candidatura de Voluntariado',
                'verbose_name_plural': 'Candidaturas de Voluntariado',
                'ordering': ['-candidatou_em'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('experiencia', models.CharField(choices=[('nenhuma', 'Nenhuma experiência'), ('basica', 'Básica'), ('intermediaria', 'Intermediária'), ('avancada', 'Avançada')], max_length=20)),
                ('motivacao', models.TextField(blank=True)),
                ('inscrito_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='home.workshop')),
            ],
            options={
                'verbose_name': 'Inscrição em Workshop',
                'verbose_name_plural': 'Inscrições em Workshops',
                'ordering': ['-inscrito_em'],
                'unique_together': {('workshop', 'email')},
            },
        ),
    ]
