# Generated by Django 5.2.5 on 2025-11-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricaoworkshop',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='inscricaoworkshop',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
    ]
