# Generated by Django 5.2.5 on 2025-11-13 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_inscricaoworkshop_confirmado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem', models.ImageField(upload_to='noticias/', verbose_name='Imagem de Capa')),
                ('categoria', models.CharField(choices=[('evento', 'Evento'), ('projeto', 'Projeto'), ('conquista', 'Conquista'), ('parceria', 'Parceria'), ('geral', 'Geral')], default='geral', max_length=20, verbose_name='Categoria')),
                ('destaque', models.BooleanField(default=False, help_text='Notícias em destaque aparecem primeiro', verbose_name='Notícia em Destaque')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-destaque', '-data_publicacao'],
            },
        ),
    ]
