# Generated by Django 5.2.5 on 2025-11-15 01:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-data_inscricao'], 'verbose_name': 'Inscrito Newsletter', 'verbose_name_plural': 'Inscritos Newsletter'},
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='inscrito_em',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Inscrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
