# Generated by Django 5.2.5 on 2025-11-15 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('evento', 'Evento'), ('projeto', 'Projeto'), ('conquista', 'Conquista'), ('parceria', 'Parceria'), ('noticia', 'Notícia Geral')], default='noticia', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora em que a notícia será publicada automaticamente', verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
