# Generated by Django 5.2.5 on 2025-11-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_noticia_options_remove_noticia_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('token', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Token de Confirmação')),
            ],
            options={
                'verbose_name': 'Inscrito na Newsletter',
                'verbose_name_plural': 'Inscritos na Newsletter',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
